# Generated by Django 3.1.3 on 2021-01-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('FeesType', models.CharField(max_length=30)),
                ('FeesAmount', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('UniversitySeatNumber', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=30)),
                ('FeesType', models.CharField(max_length=30)),
                ('FeesAmount', models.IntegerField(default=0)),
                ('Date', models.DateField(default='2021-01-01')),
                ('Time', models.TimeField(default='00:00:00')),
            ],
            options={
                'db_table': 'PaymentRecord',
            },
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='StudentFeesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('UniversitySeatNumber', models.CharField(max_length=30)),
                ('CollegeFees', models.IntegerField(default=0)),
                ('ExamFees', models.IntegerField(default=0)),
                ('HostelFees', models.IntegerField(default=0)),
                ('MessFees', models.IntegerField(default=0)),
                ('BusFees', models.IntegerField(default=0)),
                ('TotalPaid', models.IntegerField(default=0)),
                ('PaymentPending', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentFeesReport',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddmissionDate', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('UniversitySeatNumber', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('Semester', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('PhoneNo', models.CharField(max_length=30)),
                ('DateOfBirth', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('PinCode', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
                ('Salary', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('PhoneNo', models.CharField(max_length=30)),
                ('DateOfBirth', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('PinCode', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
