# Generated by Django 3.1.3 on 2021-01-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='studentfeesreport',
            name='PaymentPending',
        ),
        migrations.RemoveField(
            model_name='studentfeesreport',
            name='TotalPaid',
        ),
    ]
