# Generated by Django 3.1.3 on 2021-05-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0004_auto_20210525_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PhoneNo',
            field=models.IntegerField(max_length=10),
        ),
    ]
