# Generated by Django 3.1.3 on 2021-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0005_auto_20210525_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='PhoneNo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
