# Generated by Django 3.1.3 on 2021-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0006_auto_20210525_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='PhoneNo',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
